service: bot-economy

provider:
  name: aws
  runtime: nodejs12.x

functions:
  bot:
    handler: handler.bot
    events:
      - http:
          path: bot-prod
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
